swagger: '2.0'
info:
  description: "This is documentation to implement further options on API's Configuration"
  version: '1.0.0'
  title: 'Argent Bank API documentation - accounts'
  termsOfService: 'http://swagger.io/terms/'
host: 'localhost:3000'
basePath: '/api/v1'
tags:
  - name: 'user'
    description: 'Register/Login/Update user'
  - name: 'transactions'
    description: 'Check and add informations to your transactions'
schemes:
  - 'https'
  - 'http'
paths:
  /user/login:
    post:
      security:
        - Bearer: []
      tags:
        - user
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      security:
        - Bearer: []
      tags:
        - user
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/UserResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - user
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/UserResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - user
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/UserResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{userID}:
    get:
      security:
        - Bearer: []
      tags:
        - 'transactions'
      summary: 'Returns all transactions from all accounts'
      description: ''
      operationId: 'getTransactions'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - name: 'userID'
          in: 'path'
          description: 'ID of transaction to return'
          required: true
          type: 'number'
        - in: 'header'
          name: 'Authorization'
          description: 'Attach Bearer JWT token'
          type: 'string'
          required: true
        - in: 'query'
          name: 'month'
          type: 'string'
          description: 'Month when the transaction has been created'
          required: false
      responses:
        '200':
          description: "User's transactions loaded"
          schema:
            $ref: '#/definitions/ApiResponseTransactions'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal Server Error'
  /transactions/{userID}/{transactionId}:
    post:
      security:
        - Bearer: []
      tags:
        - 'transaction'
      summary: 'Create a transaction details by ID'
      description: ''
      operationId: 'createTransaction'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - name: 'userID'
          in: 'path'
          description: 'ID of user to return'
          required: true
          type: 'number'
        - name: 'transactionId'
          in: 'path'
          description: 'ID of transaction to return'
          required: true
          type: 'number'
        - in: 'header'
          name: 'Authorization'
          description: 'Attach Bearer JWT token'
          type: 'string'
          required: true
        - in: 'body'
          name: 'body'
          description: 'Transaction Payload'
          required: true
          schema:
            $ref: '#/definitions/TransactionDetails'
      responses:
        '200':
          description: 'Transaction created'
          schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: 'Bad request'
        '500':
          description: 'Internal Server Error'
    get:
      security:
        - Bearer: []
      tags:
        - 'transaction'
      summary: 'Returns a transaction details by ID'
      description: ''
      operationId: 'getTransaction'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - name: 'userID'
          in: 'path'
          description: 'ID of user to return'
          required: true
          type: 'number'
        - name: 'transactionId'
          in: 'path'
          description: 'ID of transaction to return'
          required: true
          type: 'number'
        - in: 'header'
          name: 'Authorization'
          description: 'Attach Bearer JWT token'
          type: 'string'
          required: true
      responses:
        '200':
          description: "User's transaction detail loaded"
          schema:
            $ref: '#/definitions/TransactionDetails'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal Server Error'
    put:
      security:
        - Bearer: []
      tags:
        - 'transaction'
      summary: 'Update Details'
      description: 'Change manually category and notes of a transaction'
      operationId: 'putDetails'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - name: 'userID'
          in: 'path'
          description: 'ID of user to return'
          required: true
          type: 'number'
        - name: 'transactionId'
          in: 'path'
          description: 'ID of transaction to return'
          required: true
          type: 'number'
        - in: 'header'
          name: 'Authorization'
          description: 'Attach Bearer JWT token'
          type: 'string'
          required: true
        - in: 'body'
          name: 'body'
          description: 'Updated details Payload'
          required: true
          schema:
            $ref: '#/definitions/UpdatedTransaction'
      responses:
        '200':
          description: "User's transactions loaded"
          schema:
            $ref: '#/definitions/TransactionDetails'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal Server Error'
    delete:
      security:
        - Bearer: []
      tags:
        - 'transaction'
      summary: 'Delete details'
      description: 'Delete all the details of a transaction'
      operationId: 'deleteDetails'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - name: 'userID'
          in: 'path'
          description: 'ID of user to return'
          required: true
          type: 'integer'
        - name: 'transactionId'
          in: 'path'
          description: 'ID of transaction to return'
          required: true
          type: 'number'
        - in: 'header'
          name: 'Authorization'
          description: 'Attach Bearer JWT token'
          type: 'string'
          required: true
      responses:
        '200':
          description: 'Transaction details delete successfully'
        '400':
          description: 'Invalid transaction ID supplied'
        '404':
          description: 'Transaction Not found'
        '500':
          description: 'Internal Server Error'

securityDefinitions:
  Bearer:
    type: 'apiKey'
    name: 'Authorization'
    in: 'header'
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  UserResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  ApiResponseTransactions:
    type: 'object'
    properties:
      status:
        type: 'number'
      message:
        type: 'string'
      body:
        type: 'array'
        description: 'array of transaction'
        items:
          type: 'object'
          properties:
            id:
              type: 'number'
              description: 'id of the transaction'
            transactionDate:
              type: 'string'
              description: 'effective date of the transaction'
            title:
              type: 'string'
              description: 'quick description of the transaction'
            amount:
              type: 'number'
              description: 'amount of the transaction'
            balance:
              type: 'number'
              description: 'total balance of the linked account'
            transactionType:
              type: 'string'
              description: 'type of the transaction'
            category:
              type: 'string'
              description: 'category of the transaction'
            notes:
              type: string
              description: 'notes of the transaction'
  UpdatedTransaction:
    type: 'object'
    properties:
      status:
        type: 'number'
      message:
        type: 'string'
      body:
        type: 'object'
        properties:
          transactionType:
            type: 'string'
            description: 'type of the transaction'
          category:
            type: 'string'
            description: 'category of this transaction'
          notes:
            type: 'string'
            description: 'personnal note of the user about this transaction'
  TransactionDetails:
    type: 'object'
    properties:
      status:
        type: 'number'
      message:
        type: 'string'
      body:
        type: 'object'
        properties:
          id:
            type: 'number'
            description: 'id of the transaction'
          transactionDate:
            type: 'string'
            description: 'effective date of the transaction'
          title:
            type: 'string'
            description: 'quick description of the transaction'
          amount:
            type: 'number'
            description: 'amount of the transaction'
          balance:
            type: 'number'
            description: 'total balance of the linked account'
          transactionType:
            type: 'string'
            description: 'type of the transaction'
          category:
            type: 'string'
            description: 'category of the transaction'
          notes:
            type: string
            description: 'notes of the transaction'
